/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Customer;

import UserInterface.mConnect.ManagemConnectJPanel;
import Business.Business;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Language;
import Business.Organization.Organization;
import Business.Tips.Tip;
import Business.UserAccount.UserAccount;
import UserInterface.Preferences.SettingsJPanel;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import org.jdesktop.swingx.JXTipOfTheDay;
import org.jdesktop.swingx.tips.DefaultTip;
import org.jdesktop.swingx.tips.DefaultTipOfTheDayModel;
import org.jdesktop.swingx.tips.TipOfTheDayModel;


public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel mainContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private Business business;
    private DB4OUtil db4oUtil = DB4OUtil.getInstance();
    /**
     * Creates new form SysadminWorkAreaJPanel
     */
    public CustomerWorkAreaJPanel(JPanel mainContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Business business) {
        initComponents();
        this.mainContainer = mainContainer;
        this.business = business;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;       
        loadScreen();
        loadLabels();
        
    }
    
    public void loadLabels(){
            btnBk.setEnabled(false);
            btnBk.setToolTipText(Language.backToolTip);
            btnHome.setToolTipText(Language.homeToolTip);
            btnSettings.setToolTipText(Language.settingsToolTip);
            btnLogout.setToolTipText(Language.logoutToolTip);
            txtWelcome.setText(Language.welcome + userAccount.getCustomer().getPerson().getLastName()+", "+userAccount.getCustomer().getPerson().getFirstName());
            lblHome.setText(Language.myHome);
            btnFlightBooking.setText(Language.flightBooking);
            btnProfile.setText(Language.MyProfile);
            btnmConnect.setToolTipText(Language.connect);
            btnBookedHistory1.setText(Language.bookedHistory);
            btnContactUs.setText(Language.contactUs);
            
    }
    
    private void loadScreen(){
        if(userAccount.getMconnectNotification()>0){
            btnmConnect.setText(String.valueOf(userAccount.getMconnectNotification()));
            btnmConnect.setToolTipText("You have new notifications");
            userAccount.setMconnectNotification(0);
        } else {
            userAccount.setMconnectNotification(0);
        }
        if(userAccount.getTipNotification()>0){
            btnFlightTips.setText(String.valueOf(userAccount.getTipNotification()));
            btnFlightTips.setToolTipText("You have new notifications");
            userAccount.setTipNotification(0);
        } else {
            userAccount.setTipNotification(0);
        }
        btnBk.setEnabled(false);
            /*btnBk.setToolTipText(Language.backToolTip);
            btnHome.setToolTipText(Language.homeToolTip);
            btnSettings.setToolTipText(Language.settingsToolTip);
            btnLogout.setToolTipText(Language.logoutToolTip);
            txtWelcome.setText(Language.welcome + userAccount.getEmployee().toString());
            lblHome.setText(Language.myHome);
            btnFlightBooking.setText(Language.medicalHistory);
            btnProfile.setText(Language.Profile);
            btnmConnect.setToolTipText(Language.connect);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        userProcessContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        btnFlightBooking = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnContactUs = new javax.swing.JButton();
        btnBookedHistory1 = new javax.swing.JButton();
        ribbonJPanel = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        txtWelcome = new javax.swing.JLabel();
        btnSettings = new javax.swing.JButton();
        btnBk = new javax.swing.JButton();
        btnFlightTips = new javax.swing.JButton();
        btnmConnect = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jSplitPane1.setDividerLocation(50);
        jSplitPane1.setDividerSize(1);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        userProcessContainer.setBackground(new java.awt.Color(255, 255, 255));
        userProcessContainer.setPreferredSize(new java.awt.Dimension(1800, 670));
        userProcessContainer.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(278, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(999, 999));

        lblHome.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblHome.setText("My Home");

        btnFlightBooking.setBackground(new java.awt.Color(255, 255, 255));
        btnFlightBooking.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnFlightBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Customer/airplane74.png"))); // NOI18N
        btnFlightBooking.setText("Flight Booking");
        btnFlightBooking.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFlightBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlightBookingActionPerformed(evt);
            }
        });

        btnProfile.setBackground(new java.awt.Color(255, 255, 255));
        btnProfile.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Customer/users73.png"))); // NOI18N
        btnProfile.setText("My Profile");
        btnProfile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnContactUs.setBackground(new java.awt.Color(255, 255, 255));
        btnContactUs.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnContactUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Customer/persons10.png"))); // NOI18N
        btnContactUs.setText("Contact Us");
        btnContactUs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnContactUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactUsActionPerformed(evt);
            }
        });

        btnBookedHistory1.setBackground(new java.awt.Color(255, 255, 255));
        btnBookedHistory1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnBookedHistory1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Customer/seo2.png"))); // NOI18N
        btnBookedHistory1.setText("Booked History");
        btnBookedHistory1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBookedHistory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookedHistory1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHome)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBookedHistory1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFlightBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnContactUs, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(412, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFlightBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBookedHistory1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContactUs, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        userProcessContainer.add(jPanel1, "card2");

        jSplitPane1.setRightComponent(userProcessContainer);

        ribbonJPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdmin/on.png"))); // NOI18N
        btnLogout.setToolTipText("Click here to logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(255, 255, 255));
        btnHome.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdmin/home18.png"))); // NOI18N
        btnHome.setToolTipText("Click here to go to the home page");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        txtWelcome.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtWelcome.setText("Welcome, ");

        btnSettings.setBackground(new java.awt.Color(255, 255, 255));
        btnSettings.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdmin/machine2.png"))); // NOI18N
        btnSettings.setToolTipText("Click here to update your settings");
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });

        btnBk.setBackground(new java.awt.Color(255, 255, 255));
        btnBk.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnBk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdmin/arrow92.png"))); // NOI18N
        btnBk.setToolTipText("Click here to go to the home page");
        btnBk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBkActionPerformed(evt);
            }
        });

        btnFlightTips.setBackground(new java.awt.Color(255, 255, 255));
        btnFlightTips.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnFlightTips.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdmin/heart254.png"))); // NOI18N
        btnFlightTips.setToolTipText("Tip of the day");
        btnFlightTips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlightTipsActionPerformed(evt);
            }
        });

        btnmConnect.setBackground(new java.awt.Color(255, 255, 255));
        btnmConnect.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnmConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdmin/global53.png"))); // NOI18N
        btnmConnect.setToolTipText("Connect with other users");
        btnmConnect.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnmConnect.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnmConnect.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnmConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmConnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ribbonJPanelLayout = new javax.swing.GroupLayout(ribbonJPanel);
        ribbonJPanel.setLayout(ribbonJPanelLayout);
        ribbonJPanelLayout.setHorizontalGroup(
            ribbonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ribbonJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 597, Short.MAX_VALUE)
                .addComponent(btnmConnect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFlightTips)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addContainerGap())
        );
        ribbonJPanelLayout.setVerticalGroup(
            ribbonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ribbonJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ribbonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ribbonJPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtWelcome))
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFlightTips, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmConnect, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jSplitPane1.setTopComponent(ribbonJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFlightBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlightBookingActionPerformed
       btnBk.setEnabled(true);
        FlightBookingJPanel flightBookingJPanel = new FlightBookingJPanel(userProcessContainer, userAccount, organization, enterprise, business);
        userProcessContainer.add("FlightBookingJPanel", flightBookingJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
       
    }//GEN-LAST:event_btnFlightBookingActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        btnBk.setEnabled(true);
        MyProfileJPanel myProfileJPanel = new MyProfileJPanel(userProcessContainer, userAccount, organization, enterprise, business);
        userProcessContainer.add("MyProfileJPanel", myProfileJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        JPanel jp = (JPanel) mainContainer.getComponent(0);
        mainContainer.removeAll();
        db4oUtil.storeSystem(business);
        CardLayout layout = (CardLayout) mainContainer.getLayout();
        mainContainer.add("homePage", jp);
        layout.next(mainContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        mainContainer.removeAll();
        CardLayout layout = (CardLayout) mainContainer.getLayout();
        mainContainer.add("workArea", userAccount.getRole().createWorkArea(mainContainer, userAccount, organization, enterprise, business));
        layout.next(mainContainer);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        // TODO add your handling code here:

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("Settings", new SettingsJPanel(userAccount, enterprise, organization));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void btnBkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBkActionPerformed
        // TODO add your handling code here:
        int count = userProcessContainer.getComponentCount();
        if(count == 2){
            btnBk.setEnabled(false);
        }
        JPanel jp = (JPanel) userProcessContainer.getComponent(count-1);
        userProcessContainer.remove(jp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBkActionPerformed

    private void btnFlightTipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlightTipsActionPerformed
        DefaultTipOfTheDayModel model1 = new DefaultTipOfTheDayModel();
        TipOfTheDayModel.Tip displayTip;
        for (Tip t : business.getTipCatalog().getTipList()) {
            displayTip = new DefaultTip("Tip", t.getDescription());
            model1.add(displayTip);
        }
        JXTipOfTheDay totd1 = new JXTipOfTheDay(model1);
        totd1.showDialog(userProcessContainer);
    }//GEN-LAST:event_btnFlightTipsActionPerformed

    private void btnmConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmConnectActionPerformed
        // TODO add your handling code here:
        btnBk.setEnabled(true);
        ManagemConnectJPanel pConnectJPanel = new ManagemConnectJPanel(userProcessContainer, userAccount, organization, enterprise, business);
        userProcessContainer.add("pConnectJPanel", pConnectJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnmConnectActionPerformed

    private void btnContactUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactUsActionPerformed
         btnBk.setEnabled(true);
        ContactUsJPanel contactUsJPanel = new ContactUsJPanel(userProcessContainer, userAccount, organization, enterprise, business);
        userProcessContainer.add("ContactUsJPanel", contactUsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnContactUsActionPerformed

    private void btnBookedHistory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookedHistory1ActionPerformed
        btnBk.setEnabled(true);
        BookingHistoryJPanel bookingHistoryJPanel = new BookingHistoryJPanel(userProcessContainer, userAccount, organization, enterprise, business);
        userProcessContainer.add("BookingHistoryJPanel", bookingHistoryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
         
    }//GEN-LAST:event_btnBookedHistory1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBk;
    private javax.swing.JButton btnBookedHistory1;
    private javax.swing.JButton btnContactUs;
    private javax.swing.JButton btnFlightBooking;
    private javax.swing.JButton btnFlightTips;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnSettings;
    private javax.swing.JButton btnmConnect;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblHome;
    private javax.swing.JPanel ribbonJPanel;
    private javax.swing.JLabel txtWelcome;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
