/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.Business;
import Business.Customer.Customer;
import Business.Customer.CustomerBookings;
import Business.Enterprise.AirlineEnterprise;
import Business.Enterprise.CustomerEnterprise;
import Business.Enterprise.Enterprise;
import Business.FlightDetails.Flight;
import Business.Language;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rakesh
 */
public class TicketDetailsJPanel extends javax.swing.JPanel {

    private Enterprise enterprise;
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Business business;
    private Flight flight;
    private int number;
    private Enterprise e;
    private String category;

    /**
     * Creates new form AddingTicketsJPanel
     */
    public TicketDetailsJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Business business, Flight flight, int number, String category) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.flight = flight;
        this.number = number;
        this.category = category;
        loadScreen();
    }

    private void loadLabels() {
        lbTicketDetails.setText(Language.ticketDetails);
        lblCPhone.setText(Language.contactNumber);

        lblExtraTicketDetails.setText(Language.extraTicketsDetails);
        lblFName.setText(Language.firstName);
        lblLName.setText(Language.lastName);
        btnBook.setText(Language.book);
    }

    public void loadScreen() {
        try {
            for (Network n : business.getNetworkList()) {
                for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                    if (e instanceof AirlineEnterprise) {
                        this.e = e;
                        addRows();
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Exception");
        }
    }

    public void addRows() {
        DefaultTableModel model = (DefaultTableModel) tblTicketDetails.getModel();
        model.setRowCount(0);
        txtFName.setText(String.valueOf(userAccount.getCustomer().getPerson().getFirstName()));
        txtLName.setText(String.valueOf(userAccount.getCustomer().getPerson().getLastName()));
        txtCPhone.setText(String.valueOf(userAccount.getCustomer().getPerson().getContactDetails().getCellPhoneNo()));
        if (number > 1) {
            for (int i = 0; i < (number - 1); i++) {
                Object[] row = new Object[3];
                row[0] = null;
                row[1] = null;
                row[2] = null;
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTicketDetails = new javax.swing.JLabel();
        lblExtraTicketDetails = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTicketDetails = new javax.swing.JTable();
        txtFName = new javax.swing.JTextField();
        lblFName = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        lblLName = new javax.swing.JLabel();
        txtCPhone = new javax.swing.JTextField();
        lblCPhone = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lbTicketDetails.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbTicketDetails.setText("Ticket Details");

        lblExtraTicketDetails.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        lblExtraTicketDetails.setText("Extra Ticket Details");

        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        tblTicketDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Contact Number"
            }
        ));
        jScrollPane1.setViewportView(tblTicketDetails);

        txtFName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblFName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblFName.setText("First Name");

        txtLName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblLName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblLName.setText("Last Name");

        txtCPhone.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblCPhone.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblCPhone.setText("Cell Phone");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTicketDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExtraTicketDetails)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFName)
                        .addGap(18, 18, 18)
                        .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lblLName)
                        .addGap(18, 18, 18)
                        .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(lblCPhone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTicketDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLName)
                    .addComponent(txtCPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCPhone)
                    .addComponent(lblFName))
                .addGap(18, 18, 18)
                .addComponent(lblExtraTicketDetails)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBook)
                .addContainerGap(278, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed

        String value;
        try {
            if (number > 1) {
                for (int i = 0; i < (number - 1); i++) {
                    for (int j = 0; j < 3; j++) {
                        value = String.valueOf(tblTicketDetails.getValueAt(i, j));
                        if (value.equals("")) {
                            JOptionPane.showMessageDialog(null, "Please enter correct values");
                            return;
                        }
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Unable to process the request");
            return;
        }

        try {
            flight.getListOfCustomers().add((userAccount.getCustomer()));
            CustomerBookings cs = new CustomerBookings();
            cs.setFlight(flight);
            cs.setNumberOfSeats(number);
            cs.setCategory(category);
            cs.setPnr(String.valueOf(flight.getFlightId()) + String.valueOf(userAccount.getCustomer().getId()));
            cs.setTraveldate(flight.getDate());
            cs.setStatus("Confirmed");
            cs.setBookingID(business.counter.getNextBookingId());
            userAccount.getCustomer().getListOfBookings().add(cs);
            if (category.equalsIgnoreCase("Economy")) {
                cs.setPrice(flight.getEconomyPrice() * number);
                flight.setBusinessCounter(flight.getEconomyCounter() + number);
            } else if (category.equalsIgnoreCase("Business")) {
                cs.setPrice(flight.getBusinessCounter() * number);
                flight.setBusinessCounter(flight.getBusinessCounter() + number);
            }

            for (int i = 0; i < (number - 1); i++) {
                Customer customer = new Customer();
                customer.setFirstName((String) tblTicketDetails.getValueAt(i, 0));
                customer.setLastName((String) tblTicketDetails.getValueAt(i, 1));
                customer.getContactDetails().setCellPhoneNo((String) tblTicketDetails.getValueAt(i, 2));
                ((CustomerEnterprise) enterprise).getCustomerDirectory().getCustomerList().add(customer);
                flight.getListOfCustomers().add(customer);
            }

            JOptionPane.showMessageDialog(null, "Booking Completed");

            BookingHistoryJPanel bookingHistoryJPanel = new BookingHistoryJPanel(userProcessContainer, userAccount, organization, enterprise, business);
            userProcessContainer.add("BookingHistoryJPanel", bookingHistoryJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Unable to process the request");
        }

    }//GEN-LAST:event_btnBookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTicketDetails;
    private javax.swing.JLabel lblCPhone;
    private javax.swing.JLabel lblExtraTicketDetails;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblLName;
    private javax.swing.JTable tblTicketDetails;
    private javax.swing.JTextField txtCPhone;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    // End of variables declaration//GEN-END:variables
}
