/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.OrganizationAdmin;

import Business.Business;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class AddEmployeeJPanel extends javax.swing.JPanel {

    private Enterprise enterprise;
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Business business;
    private ManageEmployeeJPanel manageEmployee;

    /**
     * Creates new form AddEmployeeJPanel
     */
    public AddEmployeeJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Business business, ManageEmployeeJPanel manageEmployee) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.manageEmployee = manageEmployee;
        clearAll();

        cmbRole.removeAllItems();
        for (Role role : organization.getSupportedRole()) {
            cmbRole.addItem(role);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddEmployee = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        lblFName = new javax.swing.JLabel();
        lblMName = new javax.swing.JLabel();
        txtMName = new javax.swing.JTextField();
        lblLName = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblAddress1 = new javax.swing.JLabel();
        txtAddress1 = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblCountry = new javax.swing.JLabel();
        txtCountry = new javax.swing.JTextField();
        lblHPhone = new javax.swing.JLabel();
        txtHPhone = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox();
        lblAddress2 = new javax.swing.JLabel();
        txtAddress2 = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        lblZip = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        lblCPhone = new javax.swing.JLabel();
        txtCPhone = new javax.swing.JTextField();
        lblRole = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblDOB1 = new javax.swing.JLabel();
        lblAvailable = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblAddEmployee.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblAddEmployee.setText("Add Employee");

        txtFName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNameActionPerformed(evt);
            }
        });

        lblFName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblFName.setText("First Name");

        lblMName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblMName.setText("Middle Name");

        txtMName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtMName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMNameActionPerformed(evt);
            }
        });

        lblLName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblLName.setText("Last Name");

        txtLName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblSSN.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblSSN.setText("SSN");

        txtSSN.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblAddress1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblAddress1.setText("Address Line 1");

        txtAddress1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblCity.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblCity.setText("City");

        txtCity.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblCountry.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblCountry.setText("Country");

        txtCountry.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblHPhone.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblHPhone.setText("Home Phone");

        txtHPhone.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblEmail.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblEmail.setText("Email");

        txtEmail.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblUserName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblUserName.setText("User Name");

        txtUserName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserNameFocusLost(evt);
            }
        });

        txtDob.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDobActionPerformed(evt);
            }
        });

        lblDOB.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblDOB.setText("DOB");

        lblGender.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblGender.setText("Gender");

        cmbGender.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        lblAddress2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblAddress2.setText("Address Line 2");

        txtAddress2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblState.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblState.setText("State");

        txtState.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblZip.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblZip.setText("ZIP");

        txtZip.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblCPhone.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblCPhone.setText("Cell Phone");

        txtCPhone.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblRole.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblRole.setText("Role");

        cmbRole.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblPassword.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblPassword.setText("Password");

        txtPassword.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblDOB1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblDOB1.setText("(DD/MM/YYYY)");

        lblAvailable.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblAvailable.setText("Role");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddEmployee)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAddress1)
                                    .addComponent(lblFName)
                                    .addComponent(lblLName)
                                    .addComponent(lblSSN)
                                    .addComponent(lblCity))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRole)
                                        .addGap(77, 77, 77)
                                        .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCountry)
                                            .addComponent(lblHPhone)
                                            .addComponent(lblEmail))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(34, 34, 34)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblUserName)
                                .addGap(37, 37, 37)
                                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCPhone)
                                    .addComponent(lblPassword)
                                    .addComponent(lblZip))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblState)
                                    .addComponent(lblGender)
                                    .addComponent(lblDOB)
                                    .addComponent(lblMName)
                                    .addComponent(lblAddress2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDOB1)
                            .addComponent(lblAvailable))))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddEmployee)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFName)
                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMName)
                    .addComponent(txtMName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLName)
                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDOB)
                    .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDOB1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGender)
                    .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress1)
                    .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress2)
                    .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblState)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCountry)
                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblZip)
                    .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHPhone)
                    .addComponent(txtHPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCPhone)
                    .addComponent(txtCPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAvailable))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmail)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUserName)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRole)
                    .addComponent(lblPassword))
                .addGap(42, 42, 42)
                .addComponent(btnSave)
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMNameActionPerformed

    private void txtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDobActionPerformed

    private void txtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try{
        String firstName = txtFName.getText().trim();
        String middleName = txtMName.getText().trim();
        String lastName = txtLName.getText().trim();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/mm/yyyy");
        Date DOB = null;
        try {
            DOB = dateFormat.parse(txtDob.getText().trim());
        } catch (Exception e) {

        }
        String SSN = txtSSN.getText().trim();
        String gender = String.valueOf(cmbGender.getSelectedItem());
        String addressLine1 = txtAddress1.getText().trim();
        String addressLine2 = txtAddress2.getText().trim();
        String city = txtCity.getText().trim();
        String state = txtState.getText().trim();
        String country = txtCountry.getText().trim();
        Integer zip = Integer.valueOf(txtZip.getText().trim());
        String homePhone = txtHPhone.getText().trim();
        String cellPhone = txtCPhone.getText().trim();
        String email = txtEmail.getText().trim();

        String userName = txtUserName.getText().trim();
        String password = txtPassword.getText().trim();

        if (userName.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(null, "Please specify valid account details.");
            return;
        }

        if (organization.getUserAccountDirectory().isAccountAvailable(userName, business)) {
            Employee employee = organization.getEmployeeDirectory().createEmployee(firstName + " " + lastName);
            organization.getUserAccountDirectory().createEmployeeUserAccount(txtUserName.getText().trim(), txtPassword.getText().trim(), employee, (Role) cmbRole.getSelectedItem());
            
            employee.setFirstName(firstName);
            employee.setMiddleName(middleName);
            employee.setLastName(lastName);
            employee.setDOB(DOB);
            employee.setSSN(SSN);
            employee.setSex(gender);
            employee.getContactDetails().setStreetAddressLine1(addressLine1);
            employee.getContactDetails().setStreetAddressLine1(addressLine2);
            employee.getContactDetails().setCity(city);
            employee.getContactDetails().setState(state);
            employee.getContactDetails().setCountry(country);
            employee.getContactDetails().setZip(zip);
            employee.getContactDetails().setPhoneNo(homePhone);
            employee.getContactDetails().setCellPhoneNo(cellPhone);
            employee.getContactDetails().setEmail(email);

            JOptionPane.showMessageDialog(null, "Employee added successfully.");
            manageEmployee.populateTable();
            clearAll();
        } else {
            JOptionPane.showMessageDialog(null, "User name not available. Please specify a unique user user name.");
        }
        } catch(Exception e){
        JOptionPane.showMessageDialog(null, "Please specify valid details.");    
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusLost
        // TODO add your handling code here:
        if (txtUserName.getText().trim().length() > 0) {
            if (organization.getUserAccountDirectory().isAccountAvailable(txtUserName.getText().trim(), business)) {
                lblAvailable.setText("Available");
                lblAvailable.setVisible(true);
                lblAvailable.setForeground(Color.GREEN);
            } else {
                lblAvailable.setText("Not Available");
                lblAvailable.setVisible(true);
                lblAvailable.setForeground(Color.RED);
            }
        }
    }//GEN-LAST:event_txtUserNameFocusLost

    public void clearAll() {
        lblAvailable.setVisible(false);
        txtFName.setText("");
        txtMName.setText("");
        txtLName.setText("");
        txtDob.setText("");
        txtSSN.setText("");
        txtAddress1.setText("");
        txtAddress2.setText("");
        txtCity.setText("");
        txtState.setText("");
        txtCountry.setText("");
        txtZip.setText("");
        txtHPhone.setText("");
        txtCPhone.setText("");
        txtEmail.setText("");
        txtUserName.setText("");
        txtPassword.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbGender;
    private javax.swing.JComboBox cmbRole;
    private javax.swing.JLabel lblAddEmployee;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblAddress2;
    private javax.swing.JLabel lblAvailable;
    private javax.swing.JLabel lblCPhone;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDOB1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHPhone;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblMName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblZip;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtCPhone;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtHPhone;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtMName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables
}
