/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.OrganizationAdmin;

import Business.Employee.Employee;
import Business.Person.Person;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;


public class ViewEmployeeJPanel extends javax.swing.JPanel {

    private Employee employee;
    private ManageEmployeeJPanel manageEmployee;

    /**
     * Creates new form ViewEmployeeJPanel
     */
    public ViewEmployeeJPanel(Employee employee, ManageEmployeeJPanel manageEmployee) {
        initComponents();
        this.employee = employee;
        this.manageEmployee = manageEmployee;

        
        txtFName.setText(employee.getFirstName());
        txtMName.setText(employee.getLastName());
        txtLName.setText(employee.getLastName());
        txtDob.setText(employee.getDOBInStringFormat());
        txtSSN.setText((employee.getSSN() == null) ? "" : String.valueOf(employee.getSSN()));
        txtAddress1.setText(employee.getContactDetails().getStreetAddressLine1());
        txtAddress2.setText(employee.getContactDetails().getStreetAddressLine2());
        txtCity.setText(employee.getContactDetails().getCity());
        txtState.setText(employee.getContactDetails().getState());
        txtCountry.setText(employee.getContactDetails().getCountry());
        txtZip.setText((employee.getContactDetails().getZip() == null) ? "" : String.valueOf(employee.getContactDetails().getZip()));
        txtHPhone.setText(employee.getContactDetails().getPhoneNo());
        txtCPhone.setText(employee.getContactDetails().getCellPhoneNo());
        txtEmail.setText(employee.getContactDetails().getEmail());
        cmbGender.setSelectedItem(employee.getSex());

        loadScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddEmployee = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        txtAddress1 = new javax.swing.JTextField();
        cmbGender = new javax.swing.JComboBox();
        lblCity = new javax.swing.JLabel();
        lblAddress2 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        txtAddress2 = new javax.swing.JTextField();
        lblCountry = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        txtCountry = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        lblHPhone = new javax.swing.JLabel();
        lblZip = new javax.swing.JLabel();
        txtHPhone = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        lblFName = new javax.swing.JLabel();
        lblMName = new javax.swing.JLabel();
        txtMName = new javax.swing.JTextField();
        lblLName = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        lblCPhone = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        txtCPhone = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        lblAddress1 = new javax.swing.JLabel();
        lblDOB1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblAddEmployee.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblAddEmployee.setText("View Employee");

        lblGender.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblGender.setText("Gender");

        txtAddress1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        cmbGender.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        lblCity.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblCity.setText("City");

        lblAddress2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblAddress2.setText("Address Line 2");

        txtCity.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txtAddress2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblCountry.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblCountry.setText("Country");

        lblState.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblState.setText("State");

        txtCountry.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txtState.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblHPhone.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblHPhone.setText("Home Phone");

        lblZip.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblZip.setText("ZIP");

        txtHPhone.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblEmail.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblEmail.setText("Email");

        txtEmail.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txtDob.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblDOB.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblDOB.setText("DOB");

        txtFName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblFName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblFName.setText("First Name");

        lblMName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblMName.setText("Middle Name");

        txtMName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblLName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblLName.setText("Last Name");

        txtZip.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txtLName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblCPhone.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblCPhone.setText("Cell Phone");

        lblSSN.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblSSN.setText("SSN");

        txtCPhone.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txtSSN.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblAddress1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblAddress1.setText("Address Line 1");

        lblDOB1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblDOB1.setText("(DD/MM/YYYY)");

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddEmployee)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCountry)
                                    .addComponent(lblHPhone)
                                    .addComponent(lblEmail))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(136, 136, 136)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAddress1)
                                    .addComponent(lblFName)
                                    .addComponent(lblLName)
                                    .addComponent(lblSSN)
                                    .addComponent(lblCity))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtFName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDOB)
                                            .addComponent(lblGender)
                                            .addComponent(lblMName))
                                        .addGap(5, 5, 5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblState)
                                            .addComponent(lblAddress2)
                                            .addComponent(lblZip)
                                            .addComponent(lblCPhone))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMName)
                                    .addComponent(txtDob)
                                    .addComponent(cmbGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lblDOB1)))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddEmployee)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFName)
                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMName)
                    .addComponent(txtMName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLName)
                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDOB)
                    .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDOB1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGender)
                    .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress1)
                    .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress2)
                    .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblState)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCountry)
                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblZip)
                    .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHPhone)
                    .addComponent(txtHPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCPhone)
                    .addComponent(txtCPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnEdit))
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            String firstName = txtFName.getText().trim();
            String middleName = txtMName.getText().trim();
            String lastName = txtLName.getText().trim();
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/mm/yyyy");
            Date DOB = null;
            try {
                DOB = dateFormat.parse(txtDob.getText().trim());
            } catch (Exception e) {

            }
            String SSN = txtSSN.getText().trim();
            String gender = String.valueOf(cmbGender.getSelectedItem());
            String addressLine1 = txtAddress1.getText().trim();
            String addressLine2 = txtAddress2.getText().trim();
            String city = txtCity.getText().trim();
            String state = txtState.getText().trim();
            String country = txtCountry.getText().trim();
            Integer zip = Integer.valueOf(txtZip.getText().trim());
            String homePhone = txtHPhone.getText().trim();
            String cellPhone = txtCPhone.getText().trim();
            String email = txtEmail.getText().trim();

            employee.setName(firstName + " " + lastName);
          
            employee.setFirstName(firstName);
            employee.setMiddleName(middleName);
            employee.setLastName(lastName);
            employee.setDOB(DOB);
            employee.setSSN(SSN);
            employee.setSex(gender);
            employee.getContactDetails().setStreetAddressLine1(addressLine1);
            employee.getContactDetails().setStreetAddressLine1(addressLine2);
            employee.getContactDetails().setCity(city);
            employee.getContactDetails().setState(state);
            employee.getContactDetails().setCountry(country);
            employee.getContactDetails().setZip(zip);
            employee.getContactDetails().setPhoneNo(homePhone);
            employee.getContactDetails().setCellPhoneNo(cellPhone);
            employee.getContactDetails().setEmail(email);

            JOptionPane.showMessageDialog(null, "Employee details updated successfully.");
            manageEmployee.populateTable();
            loadScreen();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please specify valid details.");
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    public void enableEdit() {
        txtFName.setEnabled(true);
        txtMName.setEnabled(true);
        txtLName.setEnabled(true);
        txtDob.setEnabled(true);
        txtSSN.setEnabled(true);
        txtAddress1.setEnabled(true);
        txtAddress2.setEnabled(true);
        txtCity.setEnabled(true);
        txtState.setEnabled(true);
        txtCountry.setEnabled(true);
        txtZip.setEnabled(true);
        txtHPhone.setEnabled(true);
        txtCPhone.setEnabled(true);
        txtEmail.setEnabled(true);
        cmbGender.setEnabled(true);
        btnSave.setEnabled(true);
        btnEdit.setEnabled(false);
    }

    public void loadScreen() {
        txtFName.setEnabled(false);
        txtMName.setEnabled(false);
        txtLName.setEnabled(false);
        txtDob.setEnabled(false);
        txtSSN.setEnabled(false);
        txtAddress1.setEnabled(false);
        txtAddress2.setEnabled(false);
        txtCity.setEnabled(false);
        txtState.setEnabled(false);
        txtCountry.setEnabled(false);
        txtZip.setEnabled(false);
        txtHPhone.setEnabled(false);
        txtCPhone.setEnabled(false);
        txtEmail.setEnabled(false);
        cmbGender.setEnabled(false);
        btnSave.setEnabled(false);
        btnEdit.setEnabled(true);
    }

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        enableEdit();
    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbGender;
    private javax.swing.JLabel lblAddEmployee;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblAddress2;
    private javax.swing.JLabel lblCPhone;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDOB1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHPhone;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblMName;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblZip;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtCPhone;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtHPhone;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtMName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables
}
