/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Inventory.Manager;

import Business.Business;
import Business.Enterprise.AirlineEnterprise;

import Business.Enterprise.Enterprise;
import Business.FlightDetails.Route;
import Business.FlightDetails.Route.routeCategory;
import Business.FlightDetails.RouteDirectory;

import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class AddRouteJPanel extends javax.swing.JPanel {

    ManageRouteJPanel manageDrugsJpanel;
    JPanel userProcessContainer;
    Enterprise enterprise;
    Business business;
    private UserAccount userAccount;
    private Organization organization;

    
    public AddRouteJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Business business, ManageRouteJPanel manageDrugsJpanel) {
        initComponents();
        this.manageDrugsJpanel = manageDrugsJpanel;
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.business = business;
        this.enterprise = enterprise;

        loadScreen();
    }

    private void loadScreen() {
        cmbCategory.removeAllItems();
        for (routeCategory rc : Route.routeCategory.values()) {
            cmbCategory.addItem(rc);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddRoute = new javax.swing.JLabel();
        txtSource = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox();
        lblCategory = new javax.swing.JLabel();
        lblBatchNumber = new javax.swing.JLabel();
        lblDrugName = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblAddRoute.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblAddRoute.setText("Add Route");

        txtSource.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txtDestination.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        cmbCategory.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Domestic", "International", " " }));

        lblCategory.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblCategory.setText("Category");

        lblBatchNumber.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblBatchNumber.setText("Destination");

        lblDrugName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblDrugName.setText("Source");

        lblDescription.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblDescription.setText("Description");

        taDescription.setColumns(20);
        taDescription.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        taDescription.setRows(5);
        jScrollPane2.setViewportView(taDescription);

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddRoute)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescription)
                            .addComponent(lblDrugName)
                            .addComponent(lblBatchNumber)
                            .addComponent(lblCategory))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDestination)
                                .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(238, 238, 238)
                                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(601, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddRoute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDrugName)
                    .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBatchNumber)
                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategory))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescription))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(276, 276, 276))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
                
                String source = txtSource.getText().trim();
                String category = String.valueOf(cmbCategory.getSelectedItem());
                String destination = txtDestination.getText().trim();
                String description = taDescription.getText().trim();

                if (source.equals("")) {
                    JOptionPane.showMessageDialog(null, "Please specify valid source name.");
                    return;
                }

                Route route = new Route();
               
                ((AirlineEnterprise) enterprise).getRouteDirectory().addRoute(route);
                route.setSource(source);
                route.setDestination(destination);
                route.setRouteCategory(category);
                route.setDescription(description);
                route.setRouteId(business.counter.getNextRouteID());

                JOptionPane.showMessageDialog(null, "Route added successfully.");
                
                clearAll();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please specify valid details.");
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void clearAll() {
        txtSource.setText("");
        txtDestination.setText("");
        taDescription.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbCategory;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddRoute;
    private javax.swing.JLabel lblBatchNumber;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDrugName;
    private javax.swing.JTextArea taDescription;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtSource;
    // End of variables declaration//GEN-END:variables
}
