/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Inventory.Manager;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Language;

import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RouteRequest;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class ManageRouteRequestsJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Enterprise enterprise;
    Business business;
    private UserAccount userAccount;
    private Organization organization;

    /**
     * Creates new form ManageOrdersJPanel
     */
    public ManageRouteRequestsJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.business = business;
        this.enterprise = enterprise;

        loadScreen();
        hideControls();
    }

    private void loadScreen() {
        cmbRequestStatus.removeAllItems();
        for (WorkRequest.OrderStatus os : WorkRequest.OrderStatus.values()) {
            
            cmbRequestStatus.addItem(os);
        }
        
    }
    
    private void hideControls(){
        
        btnDisapprove.setEnabled(false);
        
    }
    
    private void showControls(){
       
       
        btnDisapprove.setEnabled(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddDrug = new javax.swing.JLabel();
        lblCategory1 = new javax.swing.JLabel();
        cmbRequestStatus = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRouteRequests = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        btnDisapprove = new javax.swing.JButton();
        lblComments = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        lblAddDrug.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblAddDrug.setText("Requests");

        lblCategory1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblCategory1.setText("Request Status");

        cmbRequestStatus.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cmbRequestStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRequestStatus(evt);
            }
        });

        tblRouteRequests.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tblRouteRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Requestor", "Request Id", "Request Date ", "Comments", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRouteRequests.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblRouteRequests.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(tblRouteRequests);

        btnAssign.setBackground(new java.awt.Color(255, 255, 255));
        btnAssign.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnAssign.setText("Assign to me");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        btnDisapprove.setBackground(new java.awt.Color(255, 255, 255));
        btnDisapprove.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnDisapprove.setText("Disapprove");
        btnDisapprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisapproveActionPerformed(evt);
            }
        });

        lblComments.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblComments.setText("Comments");

        taDescription.setColumns(20);
        taDescription.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        taDescription.setRows(5);
        jScrollPane3.setViewportView(taDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblAddDrug)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnDisapprove)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnAssign))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCategory1)
                                        .addGap(33, 33, 33)
                                        .addComponent(cmbRequestStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblComments)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddDrug)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategory1)
                    .addComponent(cmbRequestStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssign)
                    .addComponent(btnDisapprove))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComments))
                .addContainerGap(208, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbRequestStatus(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRequestStatus
        // TODO add your handling code here:        
        populateTable();
        if(cmbRequestStatus.getSelectedItem().toString().equalsIgnoreCase(WorkRequest.OrderStatus.Review.getValue())){
            showControls();
        } else {
            hideControls();
        }
    }//GEN-LAST:event_cmbRequestStatus

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = tblRouteRequests.getSelectedRow();
            if (selectedRow >= 0) {
                RouteRequest request = (RouteRequest) tblRouteRequests.getValueAt(selectedRow, 0);
                request.setReceiver(userAccount);
                request.setStatus(WorkRequest.OrderStatus.Review.getValue());
                cmbRequestStatus.setSelectedItem(WorkRequest.OrderStatus.Review);
            } else {
                JOptionPane.showMessageDialog(null, Language.selectEntry);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Language.selectEntry);
        }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnDisapproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisapproveActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = tblRouteRequests.getSelectedRow();
            if (selectedRow >= 0) {
                RouteRequest request = (RouteRequest) tblRouteRequests.getValueAt(selectedRow, 0);
                request.setComments(taDescription.getText());
                request.setStatus(WorkRequest.OrderStatus.Disapproved.getValue());
                DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");        
                request.setResolveDate(dateFormat.format(new Date()));
                request.setReceiver(userAccount);
                cmbRequestStatus.setSelectedItem(WorkRequest.OrderStatus.Disapproved);
            } else {
                JOptionPane.showMessageDialog(null, Language.selectEntry);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Language.selectEntry);
        }
    }//GEN-LAST:event_btnDisapproveActionPerformed

   

    public void populateTable() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) tblRouteRequests.getModel();
            dtm.setRowCount(0);
            for (WorkRequest wr : enterprise.getWorkQueue().getWorkRequestList()) {

                if (((RouteRequest) wr).getStatus().equalsIgnoreCase(cmbRequestStatus.getSelectedItem().toString())) {
                    if("Route Request".equals(wr.getRequestType())){
                Object row[] = new Object[5];
                row[0] = wr.getSender();
                row[1] = wr.getWorkRequestId();
                row[2] = wr.getRequestDate();
                row[3] = wr.getComments();
                row[4] = wr.getStatus();
                dtm.addRow(row);
            }
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Unable to display requests");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnDisapprove;
    private javax.swing.JComboBox cmbRequestStatus;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAddDrug;
    private javax.swing.JLabel lblCategory1;
    private javax.swing.JLabel lblComments;
    private javax.swing.JTextArea taDescription;
    private javax.swing.JTable tblRouteRequests;
    // End of variables declaration//GEN-END:variables
}
