/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Inventory.Manager;

import Business.Business;
import Business.Enterprise.AirlineEnterprise;
import Business.Enterprise.Enterprise;
import Business.FlightDetails.Route;

import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class ViewRouteJPanel extends javax.swing.JPanel {

    ManageRouteJPanel manageDrugsJpanel;
    Route route;
    Business business;
    Enterprise enterprise;

    /**
     * Creates new form AddDrugJPanel
     */
    public ViewRouteJPanel(Enterprise enterprise, Business business,Route route, ManageRouteJPanel manageDrugsJpanel) {
        initComponents();
        this.manageDrugsJpanel = manageDrugsJpanel;
        this.route = route;
        this.enterprise = enterprise;
        this.business = business;

        txtRouteID.setText(String.valueOf(route.getRouteId()));
        cmbCategory.setSelectedItem(route.getRouteCategory());
        txtSource.setText(route.getSource());
        txtDestination.setText(route.getDestination());
        taDescription.setText(route.getDescription());
        loadScreen();
    }

    private void loadScreen() {
        cmbCategory.removeAllItems();
        for (Route.routeCategory rc : Route.routeCategory.values()) {
            cmbCategory.addItem(rc);
        }

        txtRouteID.setEnabled(false);
        cmbCategory.setEnabled(false);
        txtSource.setEnabled(false);
        txtDestination.setEnabled(false);
        taDescription.setEnabled(false);
        btnEdit.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewDrug = new javax.swing.JLabel();
        txtRouteID = new javax.swing.JTextField();
        lblDrugName = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtSource = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox();
        lblCategory = new javax.swing.JLabel();
        lblBatchNumber = new javax.swing.JLabel();
        lblDrugName1 = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        lblViewDrug.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblViewDrug.setText("View Route");

        txtRouteID.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblDrugName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblDrugName.setText("Route Id");

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        txtSource.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txtDestination.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        cmbCategory.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Domestic", "International", " " }));
        cmbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategory(evt);
            }
        });

        lblCategory.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblCategory.setText("Category");

        lblBatchNumber.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblBatchNumber.setText("Destination");

        lblDrugName1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblDrugName1.setText("Source");

        lblDescription.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblDescription.setText("Description");

        taDescription.setColumns(20);
        taDescription.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        taDescription.setRows(5);
        jScrollPane2.setViewportView(taDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewDrug)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDrugName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(txtRouteID, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDrugName1)
                                    .addComponent(lblBatchNumber)
                                    .addComponent(lblCategory)
                                    .addComponent(lblDescription))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtDestination)
                                        .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(131, 131, 131)
                                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(591, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblViewDrug)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDrugName)
                    .addComponent(txtRouteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDrugName1)
                    .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBatchNumber)
                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategory))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lblDescription))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnSave))
                .addGap(69, 69, 69))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            String source = txtSource.getText().trim();
                String category = String.valueOf(cmbCategory.getSelectedItem());
                String destination = txtDestination.getText().trim();
                String description = taDescription.getText().trim();
            
            

          if (source.equals("")) {
                    JOptionPane.showMessageDialog(null, "Please specify valid source name.");
                    return;
                }

                Route route = new Route();
                ((AirlineEnterprise) enterprise).getOrganization().getRouteDirectory().addRoute(route);
                route.setSource(source);
                route.setDestination(destination);
                route.setRouteCategory(category);
                route.setDescription(description);
                
            JOptionPane.showMessageDialog(null, "Route updated successfully.");
            
            //manageRouteJpanel.populateTable((Route) cmbRoute.getSelectedItem());
            loadScreen();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please specify valid details.");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void enableEdit() {
        txtRouteID.setEnabled(true);
        cmbCategory.setEnabled(true);
        txtSource.setEnabled(true);
        txtDestination.setEnabled(true);
        taDescription.setEnabled(true);
        btnSave.setEnabled(true);
        btnEdit.setEnabled(false);
    }

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        enableEdit();
    }//GEN-LAST:event_btnEditActionPerformed

    private void cmbCategory(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategory
        // TODO add your handling code here:
        cmbCategory.removeAllItems();
        for (Route route : business.getRouteDirectory().getListOfRoute()) {
            if (route.getRouteCategory().equalsIgnoreCase(String.valueOf(cmbCategory.getSelectedItem()))) {
                cmbCategory.addItem(route);
            }
            else {
                JOptionPane.showMessageDialog(null, "Not a correct category", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cmbCategory


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbCategory;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBatchNumber;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDrugName;
    private javax.swing.JLabel lblDrugName1;
    private javax.swing.JLabel lblViewDrug;
    private javax.swing.JTextArea taDescription;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtRouteID;
    private javax.swing.JTextField txtSource;
    // End of variables declaration//GEN-END:variables
}
