/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;

import Business.Business;
import Business.Enterprise.CustomerEnterprise;
import Business.Enterprise.Enterprise;
import Business.Language;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Tips.Tip;
import Business.UserAccount.UserAccount;
import java.text.SimpleDateFormat;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class ManageTipsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Business business;
    private SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageTipsJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;

        clearFields();
        loadScreen();
    }

    public void clearFields() {
        taDescription.setText("");
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblTips.getModel();
        Collections.sort(business.getTipCatalog().getTipList());
        model.setRowCount(0);
        for (Tip t : business.getTipCatalog().getTipList()) {
            Object[] row = new Object[2];
            row[0] = t;
            row[1] = dateFormat.format(t.getAddedDate());
            model.addRow(row);
        }

    }

    private void loadScreen() {

        populateTable();
        /*
         lblManageDisease.setText(Language.manageEnterprise);
         lblAvailableEnterprise.setText(Language.availableEnterprise);
         lblAddNewEnterprise.setText(Language.addNewEnterprise);
         lblNetworkName.setText(Language.networkName);
         lblEnterpriseType.setText(Language.enterpriseType);
         lblEnterpriseName.setText(Language.enterpriseName);
         btnSave.setText(Language.save);
         btnSave.setToolTipText(Language.saveTT);
         tblDisease.getTableHeader().getColumnModel().getColumn(0).setHeaderValue(Language.enterpriseName);
         tblDisease.getTableHeader().getColumnModel().getColumn(1).setHeaderValue(Language.networkName);
         tblDisease.getTableHeader().getColumnModel().getColumn(2).setHeaderValue(Language.enterpriseType);
         btnDelete.setText(Language.delete);
         btnDelete.setToolTipText(Language.deleteTT);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTips = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        lblManageDisease = new javax.swing.JLabel();
        lblAddNewEnterprise = new javax.swing.JLabel();
        lblAvailableEnterprise = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        lblEnterpriseName1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 720));

        tblTips.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tblTips.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Description", "Added Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTips.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblTips.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblTips);

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnSave.setText("Submit");
        btnSave.setActionCommand("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblManageDisease.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblManageDisease.setText("Manage Tips");

        lblAddNewEnterprise.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblAddNewEnterprise.setText("Add New Tip");

        lblAvailableEnterprise.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblAvailableEnterprise.setText("Registered Tips");

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblEnterpriseName1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblEnterpriseName1.setText("Description");

        taDescription.setColumns(20);
        taDescription.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        taDescription.setRows(5);
        jScrollPane2.setViewportView(taDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnSave)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblAvailableEnterprise))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblManageDisease)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEnterpriseName1)
                                            .addComponent(lblAddNewEnterprise)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jScrollPane1))))
                .addContainerGap(400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblManageDisease)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAddNewEnterprise)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEnterpriseName1)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addGap(21, 21, 21)
                .addComponent(lblAvailableEnterprise)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            if (!taDescription.getText().isEmpty()) {
                Tip tip = business.getTipCatalog().addTip();
                tip.setDescription(taDescription.getText().trim());
                clearFields();
                populateTable();
                JOptionPane.showMessageDialog(null, "Tip added successfully.");
            } else {
                JOptionPane.showMessageDialog(null, "Please specify the tip.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Unable to create the tip.");
        }

        for (Network n : business.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount ua : e.getUserAccountDirectory().getUserAccountList()) {
                    ua.setTipNotification(ua.getTipNotification() + 1);
                }
            }
        }
        for (Network n : business.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (!(e instanceof CustomerEnterprise)) {
                    for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                        for (UserAccount ua : o.getUserAccountDirectory().getUserAccountList()) {
                            ua.setTipNotification(ua.getTipNotification() + 1);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = tblTips.getSelectedRow();
            if (selectedRow >= 0) {
                int dialogResult = JOptionPane.showConfirmDialog(null, Language.confirmDelete, "Warning", JOptionPane.YES_NO_OPTION);
                if (dialogResult == JOptionPane.YES_OPTION) {

                    business.getTipCatalog().deleteTip((Tip) tblTips.getValueAt(selectedRow, 0));
                    JOptionPane.showMessageDialog(null, Language.successDelete);
                    populateTable();
                }
            } else {
                JOptionPane.showMessageDialog(null, Language.selectEntry);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Language.fail);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddNewEnterprise;
    private javax.swing.JLabel lblAvailableEnterprise;
    private javax.swing.JLabel lblEnterpriseName1;
    private javax.swing.JLabel lblManageDisease;
    private javax.swing.JTextArea taDescription;
    private javax.swing.JTable tblTips;
    // End of variables declaration//GEN-END:variables
}
