/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Language;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class ManageNetworksJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Business business;    

    /**
     * Creates new form ManageNetworksJPanel
     */
    public ManageNetworksJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        loadScreen();
        populateTable();
        lblAvailable.setVisible(false);
    }

    private void loadScreen() {
        
        
        lblManageNetworks.setText(Language.manageNetwork);
        lblAvailableNetwork.setText(Language.availableNetwork);
        lblAddNewNetwork.setText(Language.addNewNetwork);
        lblNetworkName.setText(Language.networkName);
        btnSave.setText(Language.save);
        
        tblNW.getTableHeader().getColumnModel().getColumn(0).setHeaderValue(Language.networkName);
        btnDelete.setText(Language.delete);
        btnDelete.setToolTipText(Language.deleteTT);
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblNW.getModel();
        model.setRowCount(0);
        for (Network network : business.getNetworkList()) {
            Object[] row = new Object[1];
            row[0] = network;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNW = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        lblNetworkName = new javax.swing.JLabel();
        txtNetworkName = new javax.swing.JTextField();
        lblManageNetworks = new javax.swing.JLabel();
        lblAvailableNetwork = new javax.swing.JLabel();
        lblAddNewNetwork = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        lblAvailable = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(964, 720));

        tblNW.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tblNW.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Network Name"
            }
        ));
        tblNW.setGridColor(new java.awt.Color(255, 255, 255));
        tblNW.setOpaque(false);
        tblNW.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblNW.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblNW);

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblNetworkName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblNetworkName.setText("Network Name");

        txtNetworkName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtNetworkName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNetworkNameFocusLost(evt);
            }
        });

        lblManageNetworks.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblManageNetworks.setText("Manage Network");

        lblAvailableNetwork.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblAvailableNetwork.setText("Available Networks");

        lblAddNewNetwork.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblAddNewNetwork.setText("Add New Network");

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblAvailable.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblAvailable.setText("Validation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblManageNetworks))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblAddNewNetwork))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblAvailableNetwork))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblNetworkName)
                        .addGap(20, 20, 20)
                        .addComponent(txtNetworkName, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAvailable)))
                .addGap(370, 416, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblManageNetworks)
                .addGap(40, 40, 40)
                .addComponent(lblAddNewNetwork)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNetworkName)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNetworkName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAvailable)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addGap(42, 42, 42)
                .addComponent(lblAvailableNetwork)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String name = txtNetworkName.getText().trim();
        if (!name.isEmpty() && (!business.isNetworkAvailable(name))) {            
            Network network = business.addNetwork(name);
            populateTable();
        } else {
            JOptionPane.showMessageDialog(null, "Please specify a valid network name.");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = tblNW.getSelectedRow();
            if (selectedRow >= 0) {
                int dialogResult = JOptionPane.showConfirmDialog(null, Language.confirmDelete, "Warning", JOptionPane.YES_NO_OPTION);
                if (dialogResult == JOptionPane.YES_OPTION) {

                    Network nw = (Network) tblNW.getValueAt(selectedRow, 0);
                    business.deleteNetwork(nw);
                    JOptionPane.showMessageDialog(null, Language.successDelete);
                    populateTable();
                }
            } else {
                JOptionPane.showMessageDialog(null, Language.selectEntry);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Language.fail);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtNetworkNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNetworkNameFocusLost
        // TODO add your handling code here:
        if(!txtNetworkName.getText().isEmpty()){
            if(business.isNetworkAvailable(txtNetworkName.getText().trim())){
                lblAvailable.setText("Network with this name already exists");
                lblAvailable.setVisible(true);
                lblAvailable.setForeground(Color.red);
            } else {
                lblAvailable.setVisible(false);
            }
        } else {
            lblAvailable.setVisible(false);
        }
    }//GEN-LAST:event_txtNetworkNameFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddNewNetwork;
    private javax.swing.JLabel lblAvailable;
    private javax.swing.JLabel lblAvailableNetwork;
    private javax.swing.JLabel lblManageNetworks;
    private javax.swing.JLabel lblNetworkName;
    private javax.swing.JTable tblNW;
    private javax.swing.JTextField txtNetworkName;
    // End of variables declaration//GEN-END:variables
}
