/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Language;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Business business;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageEnterpriseJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;

        cmbNW.removeAllItems();
        for (Network network : business.getNetworkList()) {
            cmbNW.addItem(network);
        }

        cmbEnt.removeAllItems();
        for (Enterprise.EnterpriseType en : Enterprise.EnterpriseType.values()) {
            if (!(en.equals(Enterprise.EnterpriseType.Customer))) {
                cmbEnt.addItem(en);
            }
            
        }

        loadScreen();
        populateTable();
    }

    private void loadScreen() {

        lblManageEnterprise.setText(Language.manageEnterprise);
        lblAvailableEnterprise.setText(Language.availableEnterprise);
        lblAddNewEnterprise.setText(Language.addNewEnterprise);
        lblNetworkName.setText(Language.networkName);
        lblEnterpriseType.setText(Language.enterpriseType);
        lblEnterpriseName.setText(Language.enterpriseName);
        btnSave.setText(Language.save);

        tblEnterprise.getTableHeader().getColumnModel().getColumn(0).setHeaderValue(Language.enterpriseName);
        tblEnterprise.getTableHeader().getColumnModel().getColumn(1).setHeaderValue(Language.networkName);
        tblEnterprise.getTableHeader().getColumnModel().getColumn(2).setHeaderValue(Language.enterpriseType);
        btnDelete.setText(Language.delete);
        btnDelete.setToolTipText(Language.deleteTT);
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblEnterprise.getModel();
        model.setRowCount(0);
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                Object[] row = new Object[3];
                row[0] = enterprise;
                row[1] = network;
                row[2] = enterprise.getEnterpriseType();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        lblNetworkName = new javax.swing.JLabel();
        lblEnterpriseType = new javax.swing.JLabel();
        lblEnterpriseName = new javax.swing.JLabel();
        cmbNW = new javax.swing.JComboBox();
        cmbEnt = new javax.swing.JComboBox();
        txtName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblManageEnterprise = new javax.swing.JLabel();
        lblAddNewEnterprise = new javax.swing.JLabel();
        lblAvailableEnterprise = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 720));

        tblEnterprise.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Network", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEnterprise.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblEnterprise.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblEnterprise);

        lblNetworkName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblNetworkName.setText("Network Name");

        lblEnterpriseType.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblEnterpriseType.setText("Enterprise Type");

        lblEnterpriseName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblEnterpriseName.setText("Enterprise Name");

        cmbNW.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cmbNW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNWActionPerformed(evt);
            }
        });

        cmbEnt.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cmbEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEntActionPerformed(evt);
            }
        });

        txtName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnSave.setText("Submit");
        btnSave.setActionCommand("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblManageEnterprise.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblManageEnterprise.setText("Manage Enterprise");

        lblAddNewEnterprise.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblAddNewEnterprise.setText("Add New Enterprise");

        lblAvailableEnterprise.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblAvailableEnterprise.setText("Available Enterprise");

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddNewEnterprise)
                            .addComponent(lblAvailableEnterprise)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblEnterpriseName)
                                                    .addComponent(lblEnterpriseType, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblNetworkName, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cmbNW, 0, 343, Short.MAX_VALUE)
                                                    .addComponent(cmbEnt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtName)))
                                            .addComponent(btnSave))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblManageEnterprise)))
                .addGap(321, 321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblManageEnterprise)
                .addGap(30, 30, 30)
                .addComponent(lblAddNewEnterprise)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNetworkName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterpriseType)
                    .addComponent(cmbEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterpriseName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addGap(26, 26, 26)
                .addComponent(lblAvailableEnterprise)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbNWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNWActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (!txtName.getText().isEmpty()) {
            if (cmbNW.getItemCount() > 0) {
                Network network = (Network) cmbNW.getSelectedItem();
                Enterprise.EnterpriseType en = (Enterprise.EnterpriseType) cmbEnt.getSelectedItem();
                network.getEnterpriseDirectory().addEnterprise(txtName.getText().trim(), en);
                populateTable();
            } else {
                JOptionPane.showMessageDialog(null, "Please select network.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please specify enterprise name.");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = tblEnterprise.getSelectedRow();
            if (selectedRow >= 0) {
                int dialogResult = JOptionPane.showConfirmDialog(null, Language.confirmDelete, "Warning", JOptionPane.YES_NO_OPTION);
                if (dialogResult == JOptionPane.YES_OPTION) {

                    Enterprise enterprise = (Enterprise) tblEnterprise.getValueAt(selectedRow, 0);
                    Network network = (Network) tblEnterprise.getValueAt(selectedRow, 1);
                    network.getEnterpriseDirectory().deleteEnterprise(enterprise);
                    JOptionPane.showMessageDialog(null, Language.successDelete);
                    populateTable();
                }
            } else {
                JOptionPane.showMessageDialog(null, Language.selectEntry);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Language.fail);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void cmbEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEntActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbEnt;
    private javax.swing.JComboBox cmbNW;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddNewEnterprise;
    private javax.swing.JLabel lblAvailableEnterprise;
    private javax.swing.JLabel lblEnterpriseName;
    private javax.swing.JLabel lblEnterpriseType;
    private javax.swing.JLabel lblManageEnterprise;
    private javax.swing.JLabel lblNetworkName;
    private javax.swing.JTable tblEnterprise;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
