/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;

import Business.Business;
import Business.Employee.Employee;
import Business.Enterprise.CustomerEnterprise;
import Business.Enterprise.Enterprise;
import Business.Language;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Role.EnterpriseAdminRole;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Business business;

    /**
     * Creates new form ManageEnterpriseAdminJPanel
     */
    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;

        populateTable();
        clearFields();
        cmbNW.removeAllItems();
        for (Network nw : business.getNetworkList()) {
            cmbNW.addItem(nw);
        }
    }

    private void loadScreen() {

        lblManageEnterpriseAdmin.setText(Language.manageEnterpriseAdmin);
        lblAddAdmin.setText(Language.addNewEnterpriseAdmin);
        lblAvailableAdmin.setText(Language.availableEnterpriseAdmin);
        lblNetworkName.setText(Language.networkName);
        lblEnterpriseName.setText(Language.enterpriseName);
        lblName.setText(Language.name);
        lblUserName.setText(Language.userName);
        lblPassword.setText(Language.password);
        btnSave.setText(Language.save);

        tblEA.getTableHeader().getColumnModel().getColumn(0).setHeaderValue(Language.enterpriseName);
        tblEA.getTableHeader().getColumnModel().getColumn(1).setHeaderValue(Language.networkName);
        tblEA.getTableHeader().getColumnModel().getColumn(2).setHeaderValue(Language.userName);

        btnDelete.setText(Language.delete);
        btnDelete.setToolTipText(Language.deleteTT);
    }

    public void populateEnterpriseCombo(Network network) {
        cmbENT.removeAllItems();
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (!(enterprise instanceof CustomerEnterprise)) {
                cmbENT.addItem(enterprise);
            }
        }
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblEA.getModel();
        model.setRowCount(0);
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (!(enterprise instanceof CustomerEnterprise)) {
                    for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                        Object[] row = new Object[4];
                        row[0] = enterprise;
                        row[1] = enterprise.getEnterpriseType().getValue();
                        row[2] = network;
                        row[3] = userAccount;
                        model.addRow(row);
                    }
                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEA = new javax.swing.JTable();
        lblNetworkName = new javax.swing.JLabel();
        lblEnterpriseName = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        cmbNW = new javax.swing.JComboBox();
        cmbENT = new javax.swing.JComboBox();
        txtUN = new javax.swing.JTextField();
        txtP = new javax.swing.JTextField();
        txtN = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblManageEnterpriseAdmin = new javax.swing.JLabel();
        lblAddAdmin = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        lblAvailableAdmin = new javax.swing.JLabel();
        lblAvailable = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tblEA.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tblEA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Enterprise Type", "Network", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEA.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblEA.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblEA);

        lblNetworkName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblNetworkName.setText("Network Name");

        lblEnterpriseName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblEnterpriseName.setText("Enterprise Name");

        lblUserName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblUserName.setText("Username");

        lblPassword.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblPassword.setText("Password");

        lblName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblName.setText("Name");

        cmbNW.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cmbNW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNWActionPerformed(evt);
            }
        });

        cmbENT.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txtUN.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtUN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUNFocusLost(evt);
            }
        });

        txtP.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txtN.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblManageEnterpriseAdmin.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblManageEnterpriseAdmin.setText("Manage Enterprise Admin");

        lblAddAdmin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblAddAdmin.setText("Add Enterprise Admin");

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblAvailableAdmin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblAvailableAdmin.setText("Enterprise Admin");

        lblAvailable.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvailableAdmin)
                            .addComponent(lblAddAdmin)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblEnterpriseName)
                                            .addComponent(lblNetworkName, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblUserName, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbENT, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbNW, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtUN, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(lblAvailable))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblManageEnterpriseAdmin)))
                .addGap(690, 690, 690))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(398, 398, 398))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblManageEnterpriseAdmin)
                .addGap(18, 18, 18)
                .addComponent(lblAddAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNetworkName))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEnterpriseName)
                    .addComponent(cmbENT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserName)
                    .addComponent(lblAvailable))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addGap(27, 27, 27)
                .addComponent(lblAvailableAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:        

        String userName = txtUN.getText().trim();
        String password = txtP.getText().trim();

        if (userName.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(null, "Please specify valid account details.");
            return;
        }
        if (cmbENT.getItemCount() > 0) {
            Enterprise en = (Enterprise) cmbENT.getSelectedItem();
            if (en.getUserAccountDirectory().isAccountAvailable(userName, business)) {
                Employee e = en.getEmployeeDirectory().createEmployee(txtN.getText());
                e.setFirstName(txtN.getText());
                en.getUserAccountDirectory().createEmployeeUserAccount(userName, password, e, new EnterpriseAdminRole());
                populateTable();
                JOptionPane.showMessageDialog(null, "User account created successfully.");
                clearFields();
            } else {
                JOptionPane.showMessageDialog(null, "User name not available. Please specify a unique user user name.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select enterprise.");
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void clearFields() {
        txtN.setText("");
        txtP.setText("");
        txtUN.setText("");
        lblAvailable.setVisible(false);
    }

    private void cmbNWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNWActionPerformed
        // TODO add your handling code here:
        populateEnterpriseCombo((Network) cmbNW.getSelectedItem());
    }//GEN-LAST:event_cmbNWActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = tblEA.getSelectedRow();
            if (selectedRow >= 0) {
                int dialogResult = JOptionPane.showConfirmDialog(null, Language.confirmDelete, "Warning", JOptionPane.YES_NO_OPTION);
                if (dialogResult == JOptionPane.YES_OPTION) {

                    Enterprise en = (Enterprise) tblEA.getValueAt(selectedRow, 0);
                    en.getEmployeeDirectory().deleteEmployee(((UserAccount) tblEA.getValueAt(selectedRow, 3)).getEmployee());
                    en.getUserAccountDirectory().deleteUserAccount((UserAccount) tblEA.getValueAt(selectedRow, 3));
                    populateTable();
                    JOptionPane.showMessageDialog(null, Language.successDelete);
                }
            } else {
                JOptionPane.showMessageDialog(null, Language.selectEntry);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Language.fail);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtUNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUNFocusLost
        // TODO add your handling code here:
        if (txtUN.getText().trim().length() > 0) {
            if (((Enterprise) cmbENT.getSelectedItem()).getUserAccountDirectory().isAccountAvailable(txtUN.getText().trim(), business)) {
                lblAvailable.setText("Available");
                lblAvailable.setVisible(true);
                lblAvailable.setForeground(Color.GREEN);
            } else {
                lblAvailable.setText("Not Available");
                lblAvailable.setVisible(true);
                lblAvailable.setForeground(Color.RED);
            }
        }
    }//GEN-LAST:event_txtUNFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbENT;
    private javax.swing.JComboBox cmbNW;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddAdmin;
    private javax.swing.JLabel lblAvailable;
    private javax.swing.JLabel lblAvailableAdmin;
    private javax.swing.JLabel lblEnterpriseName;
    private javax.swing.JLabel lblManageEnterpriseAdmin;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNetworkName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTable tblEA;
    private javax.swing.JTextField txtN;
    private javax.swing.JTextField txtP;
    private javax.swing.JTextField txtUN;
    // End of variables declaration//GEN-END:variables
}
