/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SystemAdmin;

import Business.Business;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Language;
import Business.Organization.Organization;
import Business.Tips.Tip;
import Business.UserAccount.UserAccount;
import UserInterface.Preferences.SettingsJPanel;
import UserInterface.mConnect.ManagemConnectJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;
import org.jdesktop.swingx.JXTipOfTheDay;
import org.jdesktop.swingx.tips.DefaultTip;
import org.jdesktop.swingx.tips.DefaultTipOfTheDayModel;
import org.jdesktop.swingx.tips.TipOfTheDayModel;



public class SysadminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel mainContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private Business business;
    private DB4OUtil db4oUtil = DB4OUtil.getInstance();
    /**
     * Creates new form SysadminWorkAreaJPanel
     */
    public SysadminWorkAreaJPanel(JPanel mainContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Business business) {
        initComponents();
        this.mainContainer = mainContainer;
        this.business = business;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;       
        loadScreen();
       
    }
    
    private void loadScreen(){
        if(userAccount.getMconnectNotification()>0){
            btnmConnect.setText(String.valueOf(userAccount.getMconnectNotification()));
            btnmConnect.setToolTipText("You have new notifications");
            userAccount.setMconnectNotification(0);
        } else {
            userAccount.setMconnectNotification(0);
        }
        
        btnBk.setEnabled(false);
        btnHome.setToolTipText(Language.homeToolTip);
        btnBk.setToolTipText(Language.backToolTip);
        btnSettings.setToolTipText(Language.settingsToolTip);
        btnLogout.setToolTipText(Language.logoutToolTip);
        txtWelcome.setText(Language.welcome + userAccount.getUsername());
        btnNetwork.setText(Language.manageNetwork);
        btnEnterprise.setText(Language.manageEnterprise);        
        btnEnterpriseAdmin.setToolTipText(Language.manageEnterpriseAdminTT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        ribbonJPanel = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        txtWelcome = new javax.swing.JLabel();
        btnSettings = new javax.swing.JButton();
        btnBk = new javax.swing.JButton();
        btnFlightTips = new javax.swing.JButton();
        btnmConnect = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnNetwork = new javax.swing.JButton();
        lblSysAdminHome = new javax.swing.JLabel();
        btnEnterprise = new javax.swing.JButton();
        btnEnterpriseAdmin = new javax.swing.JButton();
        btnManageTips = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jSplitPane1.setDividerLocation(50);
        jSplitPane1.setDividerSize(1);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        ribbonJPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdmin/on.png"))); // NOI18N
        btnLogout.setToolTipText("Click here to logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(255, 255, 255));
        btnHome.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdmin/home18.png"))); // NOI18N
        btnHome.setToolTipText("Click here to go to the home page");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        txtWelcome.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtWelcome.setText("Welcome, ");

        btnSettings.setBackground(new java.awt.Color(255, 255, 255));
        btnSettings.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdmin/machine2.png"))); // NOI18N
        btnSettings.setToolTipText("Click here to update your settings");
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });

        btnBk.setBackground(new java.awt.Color(255, 255, 255));
        btnBk.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnBk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdmin/arrow92.png"))); // NOI18N
        btnBk.setToolTipText("Click here to go to the home page");
        btnBk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBkActionPerformed(evt);
            }
        });

        btnFlightTips.setBackground(new java.awt.Color(255, 255, 255));
        btnFlightTips.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnFlightTips.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdmin/heart254.png"))); // NOI18N
        btnFlightTips.setToolTipText("Tip of the day");
        btnFlightTips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlightTipsActionPerformed(evt);
            }
        });

        btnmConnect.setBackground(new java.awt.Color(255, 255, 255));
        btnmConnect.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnmConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdmin/global53.png"))); // NOI18N
        btnmConnect.setToolTipText("Connect with other users");
        btnmConnect.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnmConnect.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnmConnect.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnmConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmConnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ribbonJPanelLayout = new javax.swing.GroupLayout(ribbonJPanel);
        ribbonJPanel.setLayout(ribbonJPanelLayout);
        ribbonJPanelLayout.setHorizontalGroup(
            ribbonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ribbonJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 597, Short.MAX_VALUE)
                .addComponent(btnmConnect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFlightTips)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addContainerGap())
        );
        ribbonJPanelLayout.setVerticalGroup(
            ribbonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ribbonJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ribbonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ribbonJPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtWelcome))
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFlightTips, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmConnect, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jSplitPane1.setTopComponent(ribbonJPanel);

        userProcessContainer.setBackground(new java.awt.Color(255, 255, 255));
        userProcessContainer.setPreferredSize(new java.awt.Dimension(1800, 670));
        userProcessContainer.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(278, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(999, 999));

        btnNetwork.setBackground(new java.awt.Color(255, 255, 255));
        btnNetwork.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnNetwork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdmin/earth16.png"))); // NOI18N
        btnNetwork.setText("Manage Network");
        btnNetwork.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNetworkActionPerformed(evt);
            }
        });

        lblSysAdminHome.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblSysAdminHome.setText("My Home");

        btnEnterprise.setBackground(new java.awt.Color(255, 255, 255));
        btnEnterprise.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnEnterprise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdmin/interface.png"))); // NOI18N
        btnEnterprise.setText("Manage Enterprise");
        btnEnterprise.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterpriseActionPerformed(evt);
            }
        });

        btnEnterpriseAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnEnterpriseAdmin.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnEnterpriseAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdmin/pilot1.png"))); // NOI18N
        btnEnterpriseAdmin.setText("Manage Enterprise Admin");
        btnEnterpriseAdmin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEnterpriseAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterpriseAdminActionPerformed(evt);
            }
        });

        btnManageTips.setBackground(new java.awt.Color(255, 255, 255));
        btnManageTips.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnManageTips.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdmin/persons10.png"))); // NOI18N
        btnManageTips.setText("Manage Tips");
        btnManageTips.setToolTipText("");
        btnManageTips.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnManageTips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageTipsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSysAdminHome)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnManageTips, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNetwork, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEnterpriseAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSysAdminHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnterpriseAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnManageTips, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        userProcessContainer.add(jPanel1, "card2");

        jSplitPane1.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        JPanel jp = (JPanel) mainContainer.getComponent(0);
        mainContainer.removeAll();
        db4oUtil.storeSystem(business);
        CardLayout layout = (CardLayout) mainContainer.getLayout();
        mainContainer.add("homePage", jp);
        layout.next(mainContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        mainContainer.removeAll();
        CardLayout layout = (CardLayout) mainContainer.getLayout();
        mainContainer.add("workArea", userAccount.getRole().createWorkArea(mainContainer, userAccount, organization, enterprise, business));
        layout.next(mainContainer);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        // TODO add your handling code here:
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("Settings", new SettingsJPanel(userAccount, enterprise, organization));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void btnNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNetworkActionPerformed
        // TODO add your handling code here:
        btnBk.setEnabled(true);
        ManageNetworksJPanel manageNetwork = new ManageNetworksJPanel(userProcessContainer,userAccount, organization, enterprise, business);
        userProcessContainer.add("ManageNW",manageNetwork);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnNetworkActionPerformed

    private void btnEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterpriseActionPerformed
        // TODO add your handling code here:
        btnBk.setEnabled(true);
        ManageEnterpriseJPanel manageEnterprise = new ManageEnterpriseJPanel(userProcessContainer,userAccount, organization, enterprise, business);
        userProcessContainer.add("ManageEnterprise",manageEnterprise);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnEnterpriseActionPerformed

    private void btnEnterpriseAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterpriseAdminActionPerformed
        // TODO add your handling code here:
        btnBk.setEnabled(true);
        ManageEnterpriseAdminJPanel manageEnterprise = new ManageEnterpriseAdminJPanel(userProcessContainer,userAccount, organization, enterprise, business);
        userProcessContainer.add("ManageEnterprise",manageEnterprise);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnEnterpriseAdminActionPerformed

    private void btnBkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBkActionPerformed
        // TODO add your handling code here:
        int count = userProcessContainer.getComponentCount();
        if(count == 2){
            btnBk.setEnabled(false);
        }
        JPanel jp = (JPanel) userProcessContainer.getComponent(count-1);
        userProcessContainer.remove(jp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBkActionPerformed

    private void btnManageTipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTipsActionPerformed
        // TODO add your handling code here:
        btnBk.setEnabled(true);
        ManageTipsJPanel manageTip = new ManageTipsJPanel(userProcessContainer,userAccount, organization, enterprise, business);
        userProcessContainer.add("ManageTips",manageTip);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
   
    }//GEN-LAST:event_btnManageTipsActionPerformed

    private void btnFlightTipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlightTipsActionPerformed
     DefaultTipOfTheDayModel model1 = new DefaultTipOfTheDayModel();
        TipOfTheDayModel.Tip displayTip;
        for (Tip t : business.getTipCatalog().getTipList()) {
            displayTip = new DefaultTip("Tip", t.getDescription());
            model1.add(displayTip);
        }
        JXTipOfTheDay totd1 = new JXTipOfTheDay(model1);
        totd1.showDialog(userProcessContainer);       
    }//GEN-LAST:event_btnFlightTipsActionPerformed

    private void btnmConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmConnectActionPerformed
        // TODO add your handling code here:
        btnBk.setEnabled(true);
        ManagemConnectJPanel pConnectJPanel = new ManagemConnectJPanel(userProcessContainer, userAccount, organization, enterprise, business);
        userProcessContainer.add("pConnectJPanel", pConnectJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnmConnectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBk;
    private javax.swing.JButton btnEnterprise;
    private javax.swing.JButton btnEnterpriseAdmin;
    private javax.swing.JButton btnFlightTips;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageTips;
    private javax.swing.JButton btnNetwork;
    private javax.swing.JButton btnSettings;
    private javax.swing.JButton btnmConnect;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblSysAdminHome;
    private javax.swing.JPanel ribbonJPanel;
    private javax.swing.JLabel txtWelcome;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
