/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EnterpriseAdmin;

import Business.Business;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Language;
import Business.Organization.Organization;
import Business.Role.AdminRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class ManageOrgAdminJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Business business;
    private Enterprise enterprise;

    /**
     * Creates new form ManageEnterpriseAdminJPanel
     */
    public ManageOrgAdminJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.enterprise = enterprise;
        populateTable();
        clearFields();
        cmbOrg.removeAllItems();
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            cmbOrg.addItem(org);
        }
    }

    private void clearFields() {
        txtN.setText("");
        txtP.setText("");
        txtUN.setText("");
        lblAvailable.setVisible(false);
    }

    private void loadScreen() {

        /*btnBack.setToolTipText(Language.backToolTip);
         lblManageOrgAdmin.setText(Language.manageEnterpriseAdmin);
         lblAddAdmin.setText(Language.addNewEnterpriseAdmin);
         lblAvailableAdmin.setText(Language.availableEnterpriseAdmin);
         lblNetworkName.setText(Language.networkName);
         lblEnterpriseName.setText(Language.enterpriseName);
         lblName.setText(Language.name);
         lblUserName.setText(Language.userName);
         lblPassword.setText(Language.password);
         btnSave.setText(Language.save);
         btnSave.setToolTipText(Language.saveTT);

         tblEA.getTableHeader().getColumnModel().getColumn(0).setHeaderValue(Language.enterpriseName);
         tblEA.getTableHeader().getColumnModel().getColumn(1).setHeaderValue(Language.networkName);
         tblEA.getTableHeader().getColumnModel().getColumn(2).setHeaderValue(Language.userName);

         btnDelete.setText(Language.delete);
         btnDelete.setToolTipText(Language.deleteTT);
         */
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblEA.getModel();
        model.setRowCount(0);
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccount userAccount : organization.getUserAccountDirectory().getUserAccountList()) {
                if (userAccount.getRole() instanceof AdminRole) {
                    Object[] row = new Object[3];
                    row[0] = organization;
                    row[1] = organization.getOrganizationType();
                    row[2] = userAccount;
                    model.addRow(row);
                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEA = new javax.swing.JTable();
        lblEnterpriseName = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        cmbOrg = new javax.swing.JComboBox();
        txtUN = new javax.swing.JTextField();
        txtP = new javax.swing.JTextField();
        txtN = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblManageOrgAdmin = new javax.swing.JLabel();
        lblAddAdmin = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        lblAvailableAdmin = new javax.swing.JLabel();
        lblAvailable = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tblEA.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tblEA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization Name", "Organization Type", "Username"
            }
        ));
        tblEA.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblEA.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblEA);

        lblEnterpriseName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblEnterpriseName.setText("Organization Name");

        lblUserName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblUserName.setText("Username");

        lblPassword.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblPassword.setText("Password");

        lblName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblName.setText("Name");

        cmbOrg.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txtUN.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtUN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUNFocusLost(evt);
            }
        });

        txtP.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txtN.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblManageOrgAdmin.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblManageOrgAdmin.setText("Manage Organization Admin");

        lblAddAdmin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblAddAdmin.setText("Add Organization Admin");

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblAvailableAdmin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblAvailableAdmin.setText("Organization Admin");

        lblAvailable.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblAvailable.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddAdmin)
                            .addComponent(lblAvailableAdmin)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblEnterpriseName)
                                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblUserName, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtUN, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblAvailable))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblManageOrgAdmin)))
                .addGap(411, 411, 411))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblManageOrgAdmin)
                .addGap(30, 30, 30)
                .addComponent(lblAddAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterpriseName)
                    .addComponent(cmbOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(lblAvailableAdmin)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:        

        String userName = txtUN.getText().trim();
        String password = txtP.getText().trim();

        if (userName.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(null, "Please specify valid account details.");
            return;
        }

        if (cmbOrg.getItemCount() > 0) {
            Organization org = (Organization) cmbOrg.getSelectedItem();
            if (org.getUserAccountDirectory().isAccountAvailable(userName, business)) {
                Employee e = org.getEmployeeDirectory().createEmployee(txtN.getText());
                e.setFirstName(txtN.getText());
                org.getUserAccountDirectory().createEmployeeUserAccount(userName, password, e, new AdminRole());
                populateTable();
                JOptionPane.showMessageDialog(null, "User account created successfully.");
                clearFields();
            } else {
                JOptionPane.showMessageDialog(null, "User name not available. Please specify a unique user user name.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select organization.");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = tblEA.getSelectedRow();
            if (selectedRow >= 0) {
                int dialogResult = JOptionPane.showConfirmDialog(null, Language.confirmDelete, "Warning", JOptionPane.YES_NO_OPTION);
                if (dialogResult == JOptionPane.YES_OPTION) {

                    Organization org = (Organization) tblEA.getValueAt(selectedRow, 0);
                    org.getUserAccountDirectory().deleteUserAccount(((UserAccount) tblEA.getValueAt(selectedRow, 2)));
                    JOptionPane.showMessageDialog(null, Language.successDelete);
                    populateTable();
                }
            } else {
                JOptionPane.showMessageDialog(null, Language.selectEntry);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Language.fail);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtUNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUNFocusLost
        // TODO add your handling code here:
        if (txtUN.getText().trim().length() > 0) {
            if (((Organization) cmbOrg.getSelectedItem()).getUserAccountDirectory().isAccountAvailable(txtUN.getText().trim(), business)) {
                lblAvailable.setText("Available");
                lblAvailable.setVisible(true);
                lblAvailable.setForeground(Color.GREEN);
            } else {
                lblAvailable.setText("Not Available");
                lblAvailable.setVisible(true);
                lblAvailable.setForeground(Color.RED);
            }
        }
    }//GEN-LAST:event_txtUNFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbOrg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddAdmin;
    private javax.swing.JLabel lblAvailable;
    private javax.swing.JLabel lblAvailableAdmin;
    private javax.swing.JLabel lblEnterpriseName;
    private javax.swing.JLabel lblManageOrgAdmin;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTable tblEA;
    private javax.swing.JTextField txtN;
    private javax.swing.JTextField txtP;
    private javax.swing.JTextField txtUN;
    // End of variables declaration//GEN-END:variables
}
