/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EnterpriseAdmin;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Language;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class ReportsJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Enterprise enterprise;
    Business business;
    private UserAccount userAccount;
    private Organization organization;

    
    public ReportsJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.business = business;
        this.enterprise = enterprise;
        loadScreen();
    }

    private void loadScreen() {
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddDrug = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblWorkQueue = new javax.swing.JTable();
        cmbQueueType = new javax.swing.JComboBox();
        lblEnterpriseName = new javax.swing.JLabel();
        lblEnterpriseName1 = new javax.swing.JLabel();
        JXWorkRequestType = new org.jdesktop.swingx.JXSearchField();
        lblEnterpriseName2 = new javax.swing.JLabel();
        JXComments = new org.jdesktop.swingx.JXSearchField();
        lblEnterpriseName3 = new javax.swing.JLabel();
        JXRequestedBy = new org.jdesktop.swingx.JXSearchField();
        lblEnterpriseName4 = new javax.swing.JLabel();
        JXRequestStatus = new org.jdesktop.swingx.JXSearchField();

        setBackground(new java.awt.Color(255, 255, 255));

        lblAddDrug.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblAddDrug.setText("Work Queue Report");

        tblWorkQueue.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tblWorkQueue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Work Request Type", "Comments", "Requested By", "Requested Date ", "Request Status", "Resolved By", "Resolved Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblWorkQueue.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblWorkQueue.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(tblWorkQueue);

        cmbQueueType.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cmbQueueType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Enterprise", "Organization" }));
        cmbQueueType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbQueueTypeActionPerformed(evt);
            }
        });

        lblEnterpriseName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblEnterpriseName.setText("Queue Type");

        lblEnterpriseName1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblEnterpriseName1.setText("Work Request Type ");

        JXWorkRequestType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JXWorkRequestTypeActionPerformed(evt);
            }
        });

        lblEnterpriseName2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblEnterpriseName2.setText("Comments");

        JXComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JXCommentsActionPerformed(evt);
            }
        });

        lblEnterpriseName3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblEnterpriseName3.setText("Requested By");

        JXRequestedBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JXRequestedByActionPerformed(evt);
            }
        });

        lblEnterpriseName4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblEnterpriseName4.setText("Request Status");

        JXRequestStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JXRequestStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnterpriseName3)
                            .addComponent(lblEnterpriseName))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbQueueType, 0, 200, Short.MAX_VALUE)
                            .addComponent(JXRequestedBy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnterpriseName1)
                            .addComponent(lblEnterpriseName4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JXWorkRequestType, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(JXRequestStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(lblEnterpriseName2)
                        .addGap(30, 30, 30)
                        .addComponent(JXComments, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAddDrug)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddDrug)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterpriseName)
                    .addComponent(cmbQueueType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnterpriseName1)
                    .addComponent(JXWorkRequestType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnterpriseName2)
                    .addComponent(JXComments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterpriseName3)
                    .addComponent(JXRequestedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnterpriseName4)
                    .addComponent(JXRequestStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbQueueTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbQueueTypeActionPerformed
        // TODO add your handling code here:
        populateTable();

    }//GEN-LAST:event_cmbQueueTypeActionPerformed

    private void JXWorkRequestTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JXWorkRequestTypeActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_JXWorkRequestTypeActionPerformed

    private void JXCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JXCommentsActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_JXCommentsActionPerformed

    private void JXRequestedByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JXRequestedByActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_JXRequestedByActionPerformed

    private void JXRequestStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JXRequestStatusActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_JXRequestStatusActionPerformed

    public void populateTable() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) tblWorkQueue.getModel();
            dtm.setRowCount(0);
            if (cmbQueueType.getSelectedItem().toString().equalsIgnoreCase("All") || cmbQueueType.getSelectedItem().toString().equalsIgnoreCase("Enterprise")) {
                for (WorkRequest workRequest : enterprise.getWorkQueue().getWorkRequestList()) {
                    if ((JXWorkRequestType.getText().trim().isEmpty() || (workRequest.getRequestType().toLowerCase().contains(JXWorkRequestType.getText().trim().toLowerCase())))
                            && (JXComments.getText().trim().isEmpty() || (workRequest.getComments().toLowerCase().contains(JXComments.getText().trim().toLowerCase())))
                            && (JXRequestedBy.getText().trim().isEmpty() || (workRequest.getSender().getEmployee().toString().toLowerCase().contains(JXRequestedBy.getText().trim().toLowerCase())))
                            && (JXRequestStatus.getText().trim().isEmpty() || (workRequest.getStatus().toLowerCase().contains(JXRequestStatus.getText().trim().toLowerCase())))) {
                        addRow(workRequest, dtm);
                    }
                } 
            } 
            if (cmbQueueType.getSelectedItem().toString().equalsIgnoreCase("All") || cmbQueueType.getSelectedItem().toString().equalsIgnoreCase("Organization")) {
                for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    for (WorkRequest workRequest : o.getWorkQueue().getWorkRequestList()) {
                        if ((JXWorkRequestType.getText().trim().isEmpty() || (workRequest.getRequestType().toLowerCase().contains(JXWorkRequestType.getText().trim().toLowerCase())))
                                && (JXComments.getText().trim().isEmpty() || (workRequest.getComments().toLowerCase().contains(JXComments.getText().trim().toLowerCase())))
                                && (JXRequestedBy.getText().trim().isEmpty() || (workRequest.getSender().getEmployee().toString().toLowerCase().contains(JXRequestedBy.getText().trim().toLowerCase())))
                                && (JXRequestStatus.getText().trim().isEmpty() || (workRequest.getStatus().toLowerCase().contains(JXRequestStatus.getText().trim().toLowerCase())))) {
                            addRow(workRequest, dtm);
                        }
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Unable to display work requests");
        }
    }

    public void addRow(WorkRequest workRequest, DefaultTableModel dtm) {
        Object row[] = new Object[7];
        row[0] = workRequest;
        row[1] = workRequest.getComments();
        row[2] = workRequest.getSender().getEmployee();
        row[3] = workRequest.getRequestDate();
        row[4] = workRequest.getStatus();
        row[5] = (workRequest.getReceiver() == null ? "" : workRequest.getReceiver().getEmployee());
        row[6] = (workRequest.getResolveDate() == null ? "" : workRequest.getResolveDate());
        dtm.addRow(row);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXSearchField JXComments;
    private org.jdesktop.swingx.JXSearchField JXRequestStatus;
    private org.jdesktop.swingx.JXSearchField JXRequestedBy;
    private org.jdesktop.swingx.JXSearchField JXWorkRequestType;
    private javax.swing.JComboBox cmbQueueType;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddDrug;
    private javax.swing.JLabel lblEnterpriseName;
    private javax.swing.JLabel lblEnterpriseName1;
    private javax.swing.JLabel lblEnterpriseName2;
    private javax.swing.JLabel lblEnterpriseName3;
    private javax.swing.JLabel lblEnterpriseName4;
    private javax.swing.JTable tblWorkQueue;
    // End of variables declaration//GEN-END:variables
}
