/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Inventory.Staff;

import Business.Business;
import Business.Enterprise.AirlineEnterprise;
import Business.Enterprise.Enterprise;
import Business.FlightDetails.Flight;
import Business.FlightDetails.Route;
import Business.Organization.AccountingOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FareRequest;
import Business.WorkQueue.WorkRequest;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rakesh
 */
public class AddFightJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    Enterprise enterprise;
    Business business;
    private UserAccount userAccount;
    private Organization organization;
    private Route route;
    /**
     * Creates new form AddFightsJPanel
     */
    public AddFightJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Business business,Route route) 
    {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.business = business;
        this.enterprise = enterprise;
        this.route = route;
        loadScreen();
    }
    public void loadScreen(){
        txtSource.setText(route.getSource());
        txtDestination.setText(route.getDestination());
        txtCategory.setText(route.getRouteCategory());
        taDescription.setText(route.getDescription());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        lblDrugName1 = new javax.swing.JLabel();
        lblAddRoute = new javax.swing.JLabel();
        txtSource = new javax.swing.JTextField();
        lblDrugName2 = new javax.swing.JLabel();
        txtDestination = new javax.swing.JTextField();
        txtBusinessSeats = new javax.swing.JTextField();
        lblDrugName3 = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        txtEconomySeats = new javax.swing.JTextField();
        lblBatchNumber = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        lblDrugName = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();
        jxDate = new org.jdesktop.swingx.JXDatePicker();

        setBackground(new java.awt.Color(255, 255, 255));

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblDrugName1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblDrugName1.setText("Date");

        lblAddRoute.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblAddRoute.setText("Add Flight");

        txtSource.setEditable(false);
        txtSource.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblDrugName2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblDrugName2.setText("Business Seats");

        txtDestination.setEditable(false);
        txtDestination.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txtBusinessSeats.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblDrugName3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblDrugName3.setText("Economy Seats");

        lblCategory.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblCategory.setText("Category");

        txtEconomySeats.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblBatchNumber.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblBatchNumber.setText("Destination");

        txtCategory.setEditable(false);
        txtCategory.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblDrugName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblDrugName.setText("Source");

        lblDescription.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblDescription.setText("Description");

        taDescription.setColumns(20);
        taDescription.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        taDescription.setRows(5);
        jScrollPane2.setViewportView(taDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddRoute)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDrugName)
                                .addComponent(lblBatchNumber)
                                .addComponent(lblCategory)
                                .addComponent(lblDrugName1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDrugName3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDrugName2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDescription)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCategory, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDestination, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSource, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jxDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBusinessSeats, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEconomySeats)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddRoute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSource, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDrugName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBatchNumber)
                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategory))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jxDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDrugName1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusinessSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDrugName2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEconomySeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDrugName3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescription))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(173, 173, 173))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {

            Date date= jxDate.getDate() ;
            Integer businessc = Integer.parseInt(txtBusinessSeats.getText().trim());
            Integer economy = Integer.parseInt(txtEconomySeats.getText().trim());
            
            Flight flight = new Flight();
            ((AirlineEnterprise) enterprise).getFlghtDirectory().addFlight(flight);
            flight.setRouteCategory(route.getRouteCategory());
            flight.setSource(route.getSource());
            flight.setDestination(route.getDestination());
            flight.setTotalBusinessSeat(businessc);
            flight.setTotalEconomySeat(economy);
            flight.setDate(date);
            flight.setDescription(taDescription.getText());
            flight.setFlightId(business.counter.getNextFlightId());
            JOptionPane.showMessageDialog(null, "Flight added successfully.");
            FareRequest fr = new FareRequest();
            for(Organization o:((AirlineEnterprise)enterprise).getOrganizationDirectory().getOrganizationList()){
                if(o instanceof AccountingOrganization){
                    //((o.getWorkQueue().getNextCounter()));
                   //TestOrder testOrder = new TestOrder(((DiagnosticCenterEnterprise) cmbServiceProvider.getSelectedItem()).getWorkQueue().getNextCounter());
                        //testOrder.setOrderType(WorkRequest.RequestCategory.TestOrder.getValue());
                        //testOrder.setSender(userAccount);
                    o.getWorkQueue().getWorkRequestList().add(fr);
                    fr.setSender(userAccount);
                    fr.setStatus(WorkRequest.OrderStatus.Processing.getValue());
                    fr.setFlight(flight);                    
                }                        
            }
            clearAll();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please specify valid details.");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void clearAll() {
        txtBusinessSeats.setText("");
        txtCategory.setText("");
        txtDestination.setText("");
        txtSource.setText("");
        txtCategory.setText("");
        taDescription.setText("");
        jxDate.setDate(null);
        txtEconomySeats.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXDatePicker jxDate;
    private javax.swing.JLabel lblAddRoute;
    private javax.swing.JLabel lblBatchNumber;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDrugName;
    private javax.swing.JLabel lblDrugName1;
    private javax.swing.JLabel lblDrugName2;
    private javax.swing.JLabel lblDrugName3;
    private javax.swing.JTextArea taDescription;
    private javax.swing.JTextField txtBusinessSeats;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtEconomySeats;
    private javax.swing.JTextField txtSource;
    // End of variables declaration//GEN-END:variables
}
