/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Inventory.Staff;

import Business.Business;
import Business.Enterprise.AirlineEnterprise;
import Business.Enterprise.Enterprise;
import Business.FlightDetails.Flight;
import Business.FlightDetails.Route;
import Business.Language;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class ManageFlightsJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Enterprise enterprise;
    Business business;
    private UserAccount userAccount;
    private Organization organization;

    /**
     * Creates new form ManageOrdersJPanel
     */
    public ManageFlightsJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.business = business;
        this.enterprise = enterprise;
        populateRoutesTable();
        populateFlightTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageFlight = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAvaliableRoutes = new javax.swing.JTable();
        lblFlightDetails = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblFlight = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnAddFlight = new javax.swing.JButton();
        lblRoutes = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblManageFlight.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblManageFlight.setText("Manage Flights");

        tblAvaliableRoutes.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tblAvaliableRoutes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Route ID", "Source", "Destination", "Category ", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAvaliableRoutes.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblAvaliableRoutes.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(tblAvaliableRoutes);

        lblFlightDetails.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblFlightDetails.setText("Flight Details");

        tblFlight.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tblFlight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight ID", "Date", "Source", "Destination", "Business Seats", "Economy Seats", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFlight.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblFlight.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane4.setViewportView(tblFlight);

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAddFlight.setBackground(new java.awt.Color(255, 255, 255));
        btnAddFlight.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnAddFlight.setText("Add Flight");
        btnAddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFlightActionPerformed(evt);
            }
        });

        lblRoutes.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblRoutes.setText("Avaliable Routes");

        btnRefresh.setBackground(new java.awt.Color(255, 255, 255));
        btnRefresh.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDelete)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblFlightDetails))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblManageFlight)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblRoutes))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnRefresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAddFlight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblManageFlight)
                .addGap(11, 11, 11)
                .addComponent(lblRoutes)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddFlight)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFlightDetails)
                    .addComponent(btnRefresh))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    try {
            
            int selectedRow = tblFlight.getSelectedRow();
            if (selectedRow >= 0) {
                 int dialogResult = JOptionPane.showConfirmDialog(null, Language.confirmDelete, "Warning", JOptionPane.YES_NO_OPTION);
                if (dialogResult == JOptionPane.YES_OPTION) {
                    ((AirlineEnterprise) enterprise).getFlghtDirectory().removeFlight((Flight) tblFlight.getValueAt(selectedRow, 0));
                    JOptionPane.showMessageDialog(null, Language.successDelete);
                    populateFlightTable();
                
            } }else {
                JOptionPane.showMessageDialog(null, Language.selectEntry);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Language.selectEntry);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFlightActionPerformed
        // TODO add your handling code here:
        try {
        int selectedRow = tblAvaliableRoutes.getSelectedRow();
        if (selectedRow >= 0) {
        
        AddFightJPanel addFlightJPanel = new AddFightJPanel(userProcessContainer, userAccount, organization, enterprise, business, (Route)tblAvaliableRoutes.getValueAt(selectedRow, 0));
        userProcessContainer.add("addFlightJPanel", addFlightJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        }
        else {
                JOptionPane.showMessageDialog(null, Language.selectEntry);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Unable to Add Flight");
        }
    }//GEN-LAST:event_btnAddFlightActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateFlightTable();
        populateRoutesTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    public void populateRoutesTable() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) tblAvaliableRoutes.getModel();
            dtm.setRowCount(0);
            for (Route r :enterprise.getRouteDirectory().getListOfRoute()) {
                Object row[] = new Object[5];
                row[0] = r;
                row[1] = r.getSource();
                row[2] = r.getDestination();
                row[3] = r.getRouteCategory();
                row[4] = r.getDescription();
                dtm.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Unable to display Routes");
        }
    }

    public void populateFlightTable() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) tblFlight.getModel();
            dtm.setRowCount(0);
            for (Flight f : ((AirlineEnterprise)enterprise).getFlghtDirectory().getListOfFlights()) {
                Object row[] = new Object[7];
                row[0] = f;
                row[1] = f.getDate();
                row[2] = f.getSource();
                row[3] = f.getDestination();
                row[4] = f.getTotalBusinessSeat();
                row[5] = f.getTotalEconomySeat();
                row[6] = f.getRouteCategory();
                dtm.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Unable to display Flights");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFlight;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblFlightDetails;
    private javax.swing.JLabel lblManageFlight;
    private javax.swing.JLabel lblRoutes;
    private javax.swing.JTable tblAvaliableRoutes;
    private javax.swing.JTable tblFlight;
    // End of variables declaration//GEN-END:variables
}
