/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Preferences;

import Business.Enterprise.Enterprise;
import Business.Language;
import Business.Organization.Organization;
import Business.Role.CustomerRole;

import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;


public class SettingsJPanel extends javax.swing.JPanel {

    private UserAccount userAccount;
    private Language language;
    private Organization organization;
    private Enterprise enterprise;

    /**
     * Creates new form UserPreferencesJPanel
     */
    public SettingsJPanel(UserAccount userAccount, Enterprise enterprise, Organization organization) {
        initComponents();

        if (!(userAccount.getRole() instanceof CustomerRole)) {
            cmbLanguage.removeItem("Spanish");
            
        }

        language = new Language();
        this.userAccount = userAccount;

        if (enterprise != null) {
            txtEnterprise.setText(enterprise.getName());
        } else {
            txtEnterprise.setText("N/A");
        }
        if (organization != null) {
            txtOrganization.setText(organization.getName());
        } else {
            txtOrganization.setText("N/A");
        }
        if ((userAccount.getRole() instanceof CustomerRole)) {
            cmbLanguage.setSelectedItem(userAccount.getPreferredLanguage());
            
        }
        

        txtRole.setText(userAccount.getRole().toString());
        loadScreen();

    }

    private void loadScreen() {

        language.updateLanguageSettings(userAccount.getPreferredLanguage());
        lblSettings.setText(language.settings);
        lblPreferedLanguage.setText(language.preferedLanguage);
        //lblMedicalHistory.setText(language.medicalHistory);
        lblRole.setText(language.role);
        btnSave.setText(language.save);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSettings = new javax.swing.JLabel();
        lblPreferedLanguage = new javax.swing.JLabel();
        cmbLanguage = new javax.swing.JComboBox();
        btnSave = new javax.swing.JButton();
        lblOrganization = new javax.swing.JLabel();
        lblEneterprise = new javax.swing.JLabel();
        txtEnterprise = new javax.swing.JTextField();
        txtOrganization = new javax.swing.JTextField();
        lblRole = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        lblSettings.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblSettings.setText("Settings");

        lblPreferedLanguage.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblPreferedLanguage.setText("Prefered Language");

        cmbLanguage.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cmbLanguage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "English", "Spanish" }));

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblOrganization.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblOrganization.setText("Organization");

        lblEneterprise.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblEneterprise.setText("Enterprise");

        txtEnterprise.setEditable(false);
        txtEnterprise.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnterpriseActionPerformed(evt);
            }
        });

        txtOrganization.setEditable(false);
        txtOrganization.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrganizationActionPerformed(evt);
            }
        });

        lblRole.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblRole.setText("Role");

        txtRole.setEditable(false);
        txtRole.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSettings)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPreferedLanguage)
                            .addComponent(lblOrganization)
                            .addComponent(lblRole)
                            .addComponent(lblEneterprise))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbLanguage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(303, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEneterprise))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrganization))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRole))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPreferedLanguage))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(243, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, language.saveSettings);
        userAccount.setPreferredLanguage(String.valueOf(cmbLanguage.getSelectedItem()));
        language.updateLanguageSettings(String.valueOf(cmbLanguage.getSelectedItem()));
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnterpriseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnterpriseActionPerformed

    private void txtOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrganizationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrganizationActionPerformed

    private void txtRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbLanguage;
    private javax.swing.JLabel lblEneterprise;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblPreferedLanguage;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSettings;
    private javax.swing.JTextField txtEnterprise;
    private javax.swing.JTextField txtOrganization;
    private javax.swing.JTextField txtRole;
    // End of variables declaration//GEN-END:variables
}
